version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB-postgres}
      - POSTGRES_USER=${POSTGRES_USER-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-postgres}
    ports:
      - 5432:5432


  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST-db}
      - POSTGRES_PORT=${POSTGRES_PORT-5432}
      - POSTGRES_USER=${POSTGRES_USER-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-postgres}
      - POSTGRES_NAME=${POSTGRES_DB-postgres}
    env_file:
      - .env
    depends_on:
      - db